import mammoth from 'mammoth';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// 读取 Word 文档
async function readDocx(filePath) {
  const result = await mammoth.extractRawText({ path: filePath });
  return result.value;
}

// 简单的英文到中文翻译（使用映射表）
const translationMap = {
  // 常见词汇
  'SHIPMENT REPORT': '发货报告',
  'Report No.': '报告编号',
  'Date': '日期',
  'Customer': '客户',
  'Order No.': '订单号',
  'Product': '产品',
  'Quantity': '数量',
  'Unit Price': '单价',
  'Total': '总计',
  'Amount': '金额',
  'Address': '地址',
  'Phone': '电话',
  'Email': '邮箱',
  'Notes': '备注',
  'Status': '状态',
  'Shipped': '已发货',
  'Pending': '待处理',
  'Completed': '已完成',
  'Cancelled': '已取消',
  'Description': '描述',
  'Item': '项目',
  'SKU': '商品编码',
  'Weight': '重量',
  'Dimensions': '尺寸',
  'Tracking': '物流跟踪',
  'Carrier': '承运商',
  'Signature': '签名',
  'Approved': '已批准',
  'Received': '已接收',
  'Payment': '付款',
  'Balance': '余额',
  'Invoice': '发票',
  'Terms': '条款',
  'Conditions': '条件',
  'Delivery': '交付',
  'Estimated': '预计',
  'Actual': '实际',
  'Contact': '联系方式',
  'Information': '信息',
  'Please': '请',
  'Thank you': '谢谢',
  'Best regards': '此致',
  'PSM': 'PSM',
  'Ltd': '有限公司',
  'Co': '公司',
  'Inc': '公司',
  'Corp': '公司',
  'January': '一月',
  'February': '二月',
  'March': '三月',
  'April': '四月',
  'May': '五月',
  'June': '六月',
  'July': '七月',
  'August': '八月',
  'September': '九月',
  'October': '十月',
  'November': '十一月',
  'December': '十二月',
  'Monday': '周一',
  'Tuesday': '周二',
  'Wednesday': '周三',
  'Thursday': '周四',
  'Friday': '周五',
  'Saturday': '周六',
  'Sunday': '周日',
  'to': '至',
  'from': '从',
  'for': '为',
  'with': '与',
  'and': '和',
  'or': '或',
  'the': '',
  'a': '',
  'an': '',
  'is': '是',
  'are': '是',
  'was': '是',
  'were': '是',
  'has been': '已经是',
  'have been': '已经是',
  'will be': '将是',
  'can': '可以',
  'could': '能够',
  'should': '应该',
  'would': '会',
  'must': '必须',
  'may': '可能',
  'might': '可能',
  'need': '需要',
  'want': '想要',
  'like': '喜欢',
  'love': '爱',
  'hate': '讨厌',
  'make': '制作',
  'create': '创建',
  'build': '建造',
  'develop': '开发',
  'design': '设计',
  'produce': '生产',
  'manufacture': '制造',
  'ship': '发货',
  'deliver': '交付',
  'send': '发送',
  'receive': '接收',
  'get': '获取',
  'take': '拿',
  'give': '给',
  'provide': '提供',
  'offer': '提供',
  'sell': '销售',
  'buy': '购买',
  'order': '订单',
  'purchase': '购买',
  'sale': '销售',
  'discount': '折扣',
  'price': '价格',
  'cost': '成本',
  'expense': '费用',
  'profit': '利润',
  'revenue': '收入',
  'budget': '预算',
  'team': '团队',
  'department': '部门',
  'company': '公司',
  'business': '业务',
  'industry': '行业',
  'market': '市场',
  'customer': '客户',
  'client': '客户',
  'supplier': '供应商',
  'vendor': '供应商',
  'partner': '合作伙伴',
  'manager': '经理',
  'director': '总监',
  'president': '总裁',
  'CEO': '首席执行官',
  'CTO': '首席技术官',
  'CFO': '首席财务官',
  'COO': '首席运营官',
  'employee': '员工',
  'staff': '员工',
  'worker': '工人',
  'assistant': '助理',
  'assistant manager': '副经理',
  'senior manager': '高级经理',
  'vice president': '副总裁',
  'executive': '高管',
  'administration': '行政部门',
  'management': '管理层',
  'operation': '运营',
  'operations': '运营',
  'finance': '财务',
  'marketing': '市场',
  'sales': '销售',
  'human resources': '人力资源',
  'HR': '人力资源',
  'IT': '信息技术',
  'research': '研究',
  'development': '开发',
  'R&D': '研发',
  'quality': '质量',
  'quality control': '质量控制',
  'quality assurance': '质量保证',
  'production': '生产',
  'logistics': '物流',
  'warehouse': '仓库',
  'inventory': '库存',
  'stock': '库存',
  'supply chain': '供应链',
  'distribution': '分销',
  'transportation': '运输',
  'shipping': '运输',
  'export': '出口',
  'import': '进口',
  'trade': '贸易',
  'international': '国际',
  'domestic': '国内',
  'local': '本地',
  'global': '全球',
  'worldwide': '全球',
  'nationwide': '全国',
  'region': '地区',
  'country': '国家',
  'city': '城市',
  'state': '州',
  'province': '省',
  'district': '区',
  'street': '街道',
  'road': '路',
  'avenue': '大道',
  'boulevard': '林荫大道',
  'building': '建筑',
  'floor': '楼层',
  'room': '房间',
  'suite': '套房',
  'unit': '单元',
  'apartment': '公寓',
  'house': '房子',
  'office': '办公室',
  'factory': '工厂',
  'warehouse': '仓库',
  'store': '商店',
  'shop': '店铺',
  'branch': '分店',
  'headquarters': '总部',
  'main office': '主办公室',
  'branch office': '分办公室',
  'remote': '远程',
  'online': '在线',
  'offline': '离线',
  'website': '网站',
  'web': '网络',
  'internet': '互联网',
  'email': '电子邮件',
  'phone': '电话',
  'mobile': '手机',
  'fax': '传真',
  'address': '地址',
  'zip code': '邮编',
  'postal code': '邮编',
  'contact number': '联系电话',
  'extension': '分机',
  'direct line': '直线',
  'hotline': '热线',
  'support': '支持',
  'service': '服务',
  'customer service': '客户服务',
  'technical support': '技术支持',
  'after-sales': '售后',
  'maintenance': '维护',
  'repair': '修理',
  'replacement': '更换',
  'refund': '退款',
  'exchange': '换货',
  'return': '退货',
  'warranty': '保修',
  'guarantee': '保证',
  'policy': '政策',
  'procedure': '程序',
  'process': '流程',
  'standard': '标准',
  'requirement': '要求',
  'specification': '规格',
  'criteria': '标准',
  'guideline': '指导方针',
  'instruction': '说明书',
  'manual': '手册',
  'document': '文档',
  'file': '文件',
  'record': '记录',
  'report': '报告',
  'summary': '摘要',
  'analysis': '分析',
  'evaluation': '评估',
  'assessment': '评估',
  'review': '审查',
  'audit': '审计',
  'inspection': '检查',
  'test': '测试',
  'testing': '测试',
  'quality test': '质量测试',
  'performance test': '性能测试',
  'stress test': '压力测试',
  'acceptance test': '验收测试',
  'validation': '验证',
  'verification': '核实',
  'certification': '认证',
  'approval': '批准',
  'authorization': '授权',
  'permission': '许可',
  'license': '许可证',
  'registration': '注册',
  'application': '申请',
  'request': '请求',
  'inquiry': '咨询',
  'proposal': '提案',
  'contract': '合同',
  'agreement': '协议',
  'terms and conditions': '条款和条件',
  'terms of service': '服务条款',
  'privacy policy': '隐私政策',
  'disclaimer': '免责声明',
  'copyright': '版权',
  'trademark': '商标',
  'patent': '专利',
  'intellectual property': '知识产权',
  'IP': '知识产权',
  'confidential': '机密',
  'proprietary': '专有',
  'sensitive': '敏感',
  'restricted': '受限',
  'public': '公开',
  'private': '私有',
  'internal': '内部',
  'external': '外部',
  'confidentiality': '保密性',
  'security': '安全性',
  'safety': '安全性',
  'risk': '风险',
  'management': '管理',
  'control': '控制',
  'monitor': '监控',
  'supervise': '监督',
  'oversee': '监督',
  'coordinate': '协调',
  'collaborate': '协作',
  'communicate': '沟通',
  'inform': '通知',
  'notify': '通知',
  'announce': '公告',
  'publish': '发布',
  'release': '发布',
  'launch': '推出',
  'introduce': '介绍',
  'present': '展示',
  'demonstrate': '演示',
  'explain': '解释',
  'describe': '描述',
  'define': '定义',
  'specify': '指定',
  'clarify': '澄清',
  'confirm': '确认',
  'verify': '核实',
  'validate': '验证',
  'authenticate': '认证',
  'authorize': '授权',
  'approve': '批准',
  'reject': '拒绝',
  'decline': '拒绝',
  'accept': '接受',
  'agree': '同意',
  'disagree': '不同意',
  'object': '反对',
  'complain': '投诉',
  'feedback': '反馈',
  'suggestion': '建议',
  'recommendation': '推荐',
  'advice': '建议',
  'opinion': '意见',
  'view': '观点',
  'perspective': '观点',
  'insight': '洞察',
  'idea': '想法',
  'concept': '概念',
  'theory': '理论',
  'principle': '原则',
  'rule': '规则',
  'regulation': '法规',
  'law': '法律',
  'legal': '法律',
  'compliance': '合规',
  'governance': '治理',
  'ethics': '道德',
  'responsibility': '责任',
  'accountability': '问责制',
  'transparency': '透明度',
  'integrity': '正直',
  'honesty': '诚实',
  'trust': '信任',
  'confidence': '信心',
  'reliability': '可靠性',
  'consistency': '一致性',
  'accuracy': '准确性',
  'precision': '精确性',
  'efficiency': '效率',
  'effectiveness': '有效性',
  'productivity': '生产力',
  'performance': '性能',
  'quality': '质量',
  'excellence': '卓越',
  'innovation': '创新',
  'creativity': '创造力',
  'improvement': '改进',
  'optimization': '优化',
  'enhancement': '增强',
  'development': '发展',
  'growth': '增长',
  'expansion': '扩展',
  'diversification': '多元化',
  'integration': '整合',
  'collaboration': '合作',
  'partnership': '合作伙伴关系',
  'alliance': '联盟',
  'cooperation': '合作',
  'coordination': '协调',
  'integration': '集成',
  'synergy': '协同效应',
  'leverage': '利用',
  'utilization': '利用',
  'deployment': '部署',
  'implementation': '实施',
  'execution': '执行',
  'operation': '运营',
  'maintenance': '维护',
  'support': '支持',
  'service': '服务',
  'solution': '解决方案',
  'product': '产品',
  'feature': '功能',
  'function': '功能',
  'capability': '能力',
  'capacity': '容量',
  'resource': '资源',
  'asset': '资产',
  'investment': '投资',
  'funding': '资金',
  'budget': '预算',
  'cost': '成本',
  'expense': '费用',
  'expenditure': '支出',
  'revenue': '收入',
  'income': '收入',
  'profit': '利润',
  'margin': '利润率',
  'ROI': '投资回报率',
  'KPI': '关键绩效指标',
  'metric': '指标',
  'measurement': '测量',
  'analysis': '分析',
  'reporting': '报告',
  'monitoring': '监控',
  'tracking': '跟踪',
  'logging': '记录',
  'audit': '审计',
  'review': '审查',
  'evaluation': '评估',
  'assessment': '评估',
  'feedback': '反馈',
  'improvement': '改进',
  'optimization': '优化',
  'enhancement': '增强',
  'upgrade': '升级',
  'update': '更新',
  'version': '版本',
  'release': '发布',
  'deployment': '部署',
  'installation': '安装',
  'configuration': '配置',
  'setup': '设置',
  'customization': '定制',
  'personalization': '个性化',
  'localization': '本地化',
  'globalization': '全球化',
  'internationalization': '国际化',
  'adaptation': '适应',
  'modification': '修改',
  'adjustment': '调整',
  'calibration': '校准',
  'tuning': '调优',
  'fine-tuning': '微调',
  'optimization': '优化',
  'streamlining': '精简',
  'simplification': '简化',
  'automation': '自动化',
  'digitization': '数字化',
  'modernization': '现代化',
  'transformation': '转型',
  'restructuring': '重组',
  'reorganization': '重组',
  'consolidation': '整合',
  'centralization': '集中化',
  'decentralization': '分散化',
  'outsourcing': '外包',
  'insourcing': '内包',
  'offshoring': '离岸外包',
  'nearshoring': '近岸外包',
  'reshoring': '回岸外包',
  'onshoring': '本土化',
  'virtualization': '虚拟化',
  'cloud': '云',
  'SaaS': '软件即服务',
  'PaaS': '平台即服务',
  'IaaS': '基础设施即服务',
  'AI': '人工智能',
  'ML': '机器学习',
  'DL': '深度学习',
  'NLP': '自然语言处理',
  'Computer Vision': '计算机视觉',
  'Robotics': '机器人技术',
  'IoT': '物联网',
  'Blockchain': '区块链',
  'Cryptocurrency': '加密货币',
  'Bitcoin': '比特币',
  'Ethereum': '以太坊',
  'Smart Contract': '智能合约',
  'Decentralized': '去中心化',
  'Distributed': '分布式',
  'Scalability': '可扩展性',
  'Reliability': '可靠性',
  'Availability': '可用性',
  'Performance': '性能',
  'Security': '安全性',
  'Privacy': '隐私',
  'Compliance': '合规',
  'Governance': '治理',
  'Risk Management': '风险管理',
  'Quality Assurance': '质量保证',
  'Quality Control': '质量控制',
  'Testing': '测试',
  'Debugging': '调试',
  'Troubleshooting': '故障排除',
  'Documentation': '文档',
  'Training': '培训',
  'Education': '教育',
  'Learning': '学习',
  'Development': '发展',
  'Research': '研究',
  'Innovation': '创新',
  'Creativity': '创造力',
  'Collaboration': '合作',
  'Communication': '沟通',
  'Leadership': '领导力',
  'Management': '管理',
  'Strategy': '战略',
  'Planning': '规划',
  'Execution': '执行',
  'Monitoring': '监控',
  'Evaluation': '评估',
  'Feedback': '反馈',
  'Improvement': '改进',
  'Success': '成功',
  'Failure': '失败',
  'Challenge': '挑战',
  'Opportunity': '机会',
  'Risk': '风险',
  'Benefit': '利益',
  'Value': '价值',
  'Impact': '影响',
  'Outcome': '结果',
  'Result': '结果',
  'Achievement': '成就',
  'Milestone': '里程碑',
  'Goal': '目标',
  'Objective': '目标',
  'Target': '目标',
  'Deadline': '截止日期',
  'Timeline': '时间线',
  'Schedule': '时间表',
  'Calendar': '日历',
  'Agenda': '议程',
  'Meeting': '会议',
  'Conference': '会议',
  'Workshop': '研讨会',
  'Seminar': '研讨会',
  'Training': '培训',
  'Webinar': '网络研讨会',
  'Presentation': '演示',
  'Demo': '演示',
  'Prototype': '原型',
  'MVP': '最小可行产品',
  'Product': '产品',
  'Service': '服务',
  'Platform': '平台',
  'System': '系统',
  'Application': '应用程序',
  'Software': '软件',
  'Hardware': '硬件',
  'Device': '设备',
  'Tool': '工具',
  'Instrument': '仪器',
  'Equipment': '设备',
  'Machine': '机器',
  'Engine': '引擎',
  'Motor': '电机',
  'Sensor': '传感器',
  'Actuator': '执行器',
  'Controller': '控制器',
  'Processor': '处理器',
  'Memory': '内存',
  'Storage': '存储',
  'Network': '网络',
  'Internet': '互联网',
  'Intranet': '内联网',
  'Extranet': '外联网',
  'VPN': '虚拟专用网络',
  'Firewall': '防火墙',
  'Router': '路由器',
  'Switch': '交换机',
  'Hub': '集线器',
  'Server': '服务器',
  'Client': '客户端',
  'Database': '数据库',
  'Data': '数据',
  'Information': '信息',
  'Knowledge': '知识',
  'Wisdom': '智慧',
  'Intelligence': '智能',
  'Automation': '自动化',
  'Robotics': '机器人技术',
  'AI': '人工智能',
  'ML': '机器学习',
  'Analytics': '分析',
  'Big Data': '大数据',
  'Cloud Computing': '云计算',
  'Edge Computing': '边缘计算',
  'Fog Computing': '雾计算',
  'Quantum Computing': '量子计算',
  'Neural Network': '神经网络',
  'Deep Learning': '深度学习',
  'Machine Learning': '机器学习',
  'Artificial Intelligence': '人工智能',
  'Natural Language Processing': '自然语言处理',
  'Computer Vision': '计算机视觉',
  'Speech Recognition': '语音识别',
  'Image Recognition': '图像识别',
  'Pattern Recognition': '模式识别',
  'Data Mining': '数据挖掘',
  'Data Science': '数据科学',
  'Data Engineering': '数据工程',
  'Data Analysis': '数据分析',
  'Business Intelligence': '商业智能',
  'Business Analytics': '商业分析',
  'Predictive Analytics': '预测分析',
  'Prescriptive Analytics': '规范性分析',
  'Descriptive Analytics': '描述性分析',
  'Diagnostic Analytics': '诊断性分析',
  'Real-time Analytics': '实时分析',
  'Batch Processing': '批处理',
  'Stream Processing': '流处理',
  'Data Pipeline': '数据管道',
  'ETL': '提取、转换、加载',
  'ELT': '提取、加载、转换',
  'Data Warehouse': '数据仓库',
  'Data Lake': '数据湖',
  'Data Mart': '数据集市',
  'Data Catalog': '数据目录',
  'Data Governance': '数据治理',
  'Data Quality': '数据质量',
  'Data Security': '数据安全',
  'Data Privacy': '数据隐私',
  'Data Protection': '数据保护',
  'Data Compliance': '数据合规',
  'Data Lifecycle': '数据生命周期',
  'Data Retention': '数据保留',
  'Data Archiving': '数据归档',
  'Data Backup': '数据备份',
  'Data Recovery': '数据恢复',
  'Disaster Recovery': '灾难恢复',
  'Business Continuity': '业务连续性',
  'Risk Management': '风险管理',
  'Compliance': '合规',
  'Audit': '审计',
  'Governance': '治理',
  'Strategy': '战略',
  'Planning': '规划',
  'Execution': '执行',
  'Monitoring': '监控',
  'Reporting': '报告',
  'Analysis': '分析',
  'Optimization': '优化',
  'Improvement': '改进',
  'Innovation': '创新',
  'Transformation': '转型',
  'Change Management': '变革管理',
  'Project Management': '项目管理',
  'Program Management': '项目群管理',
  'Portfolio Management': '组合管理',
  'Resource Management': '资源管理',
  'Time Management': '时间管理',
  'Cost Management': '成本管理',
  'Quality Management': '质量管理',
  'Risk Management': '风险管理',
  'Stakeholder Management': '利益相关者管理',
  'Communication Management': '沟通管理',
  'Integration Management': '整合管理',
  'Scope Management': '范围管理',
  'Schedule Management': '进度管理',
  'Budget Management': '预算管理',
  'Contract Management': '合同管理',
  'Procurement': '采购',
  'Supply Chain': '供应链',
  'Logistics': '物流',
  'Inventory': '库存',
  'Warehouse': '仓库',
  'Distribution': '分销',
  'Transportation': '运输',
  'Shipping': '运输',
  'Delivery': '交付',
  'Customer Service': '客户服务',
  'Support': '支持',
  'Maintenance': '维护',
  'Operations': '运营',
  'Production': '生产',
  'Manufacturing': '制造',
  'Assembly': '组装',
  'Fabrication': '制造',
  'Processing': '加工',
  'Packaging': '包装',
  'Labeling': '贴标',
  'Quality Control': '质量控制',
  'Quality Assurance': '质量保证',
  'Testing': '测试',
  'Inspection': '检查',
  'Audit': '审计',
  'Certification': '认证',
  'Compliance': '合规',
  'Regulation': '法规',
  'Standard': '标准',
  'Specification': '规格',
  'Requirement': '要求',
  'Design': '设计',
  'Engineering': '工程',
  'R&D': '研发',
  'Innovation': '创新',
  'Research': '研究',
  'Development': '开发',
  'Prototyping': '原型设计',
  'Testing': '测试',
  'Validation': '验证',
  'Verification': '核实',
  'Documentation': '文档',
  'Training': '培训',
  'Support': '支持',
  'Service': '服务',
  'Solution': '解决方案',
  'Product': '产品',
  'Feature': '功能',
  'Benefit': '利益',
  'Value': '价值',
  'Cost': '成本',
  'Price': '价格',
  'Margin': '利润率',
  'Profit': '利润',
  'Revenue': '收入',
  'Sales': '销售',
  'Marketing': '市场',
  'Advertising': '广告',
  'Promotion': '促销',
  'Campaign': '活动',
  'Event': '活动',
  'Brand': '品牌',
  'Identity': '标识',
  'Image': '形象',
  'Reputation': '声誉',
  'Loyalty': '忠诚度',
  'Satisfaction': '满意度',
  'Experience': '体验',
  'Engagement': '参与度',
  'Conversion': '转化',
  'Retention': '留存',
  'Acquisition': '获取',
  'Churn': '流失',
  'Lifetime Value': '生命周期价值',
  'Customer Acquisition Cost': '客户获取成本',
  'Return on Investment': '投资回报率',
  'Return on Ad Spend': '广告支出回报率',
  'Click-Through Rate': '点击率',
  'Conversion Rate': '转化率',
  'Bounce Rate': '跳出率',
  'Time on Site': '停留时间',
  'Pages per Visit': '每次访问页面数',
  'Unique Visitors': '独立访客',
  'Page Views': '页面浏览量',
  'Sessions': '会话',
  'Users': '用户',
  'Active Users': '活跃用户',
  'New Users': '新用户',
  'Returning Users': '回头用户',
  'Mobile Users': '移动用户',
  'Desktop Users': '桌面用户',
  'Tablet Users': '平板用户',
  'Browser': '浏览器',
  'Device': '设备',
  'Operating System': '操作系统',
  'Platform': '平台',
  'Application': '应用程序',
  'Website': '网站',
  'Webpage': '网页',
  'Landing Page': '着陆页',
  'Homepage': '首页',
  'Navigation': '导航',
  'Menu': '菜单',
  'Search': '搜索',
  'Filter': '筛选',
  'Sort': '排序',
  'Pagination': '分页',
  'Responsive': '响应式',
  'Adaptive': '自适应',
  'Mobile-First': '移动优先',
  'User Experience': '用户体验',
  'User Interface': '用户界面',
  'Interaction Design': '交互设计',
  'Visual Design': '视觉设计',
  'Graphic Design': '平面设计',
  'UX': '用户体验',
  'UI': '用户界面',
  'Wireframe': '线框图',
  'Prototype': '原型',
  'Mockup': '模型',
  'Design System': '设计系统',
  'Component Library': '组件库',
  'Style Guide': '风格指南',
  'Brand Guidelines': '品牌指南',
  'Design Guidelines': '设计指南',
  'Development Guidelines': '开发指南',
  'Coding Standards': '编码标准',
  'Best Practices': '最佳实践',
  'Patterns': '模式',
  'Principles': '原则',
  'Guidelines': '指导方针',
  'Standards': '标准',
  'Specifications': '规格',
  'Documentation': '文档',
  'Code Review': '代码审查',
  'Peer Review': '同行评审',
  'Testing': '测试',
  'Quality Assurance': '质量保证',
  'Continuous Integration': '持续集成',
  'Continuous Deployment': '持续部署',
  'Continuous Delivery': '持续交付',
  'DevOps': '开发运维',
  'Agile': '敏捷',
  'Scrum': '敏捷开发',
  'Kanban': '看板',
  'Waterfall': '瀑布',
  'Lean': '精益',
  'Sprint': '冲刺',
  'Iteration': '迭代',
  'Release': '发布',
  'Version': '版本',
  'Deployment': '部署',
  'Environment': '环境',
  'Development': '开发',
  'Staging': '预发布',
  'Production': '生产',
  'Testing': '测试',
  'QA': '质量保证',
  'UAT': '用户验收测试',
  'Performance': '性能',
  'Scalability': '可扩展性',
  'Reliability': '可靠性',
  'Availability': '可用性',
  'Security': '安全性',
  'Performance Testing': '性能测试',
  'Load Testing': '负载测试',
  'Stress Testing': '压力测试',
  'Security Testing': '安全测试',
  'Penetration Testing': '渗透测试',
  'Vulnerability Assessment': '漏洞评估',
  'Risk Assessment': '风险评估',
  'Threat Analysis': '威胁分析',
  'Incident Response': '事件响应',
  'Disaster Recovery': '灾难恢复',
  'Business Continuity': '业务连续性',
  'Compliance': '合规',
  'Audit': '审计',
  'Governance': '治理',
  'Risk Management': '风险管理',
  'Data Privacy': '数据隐私',
  'Data Security': '数据安全',
  'Information Security': '信息安全',
  'Cybersecurity': '网络安全',
  'Network Security': '网络安全',
  'Application Security': '应用安全',
  'Cloud Security': '云安全',
  'Mobile Security': '移动安全',
  'IoT Security': '物联网安全',
  'Blockchain Security': '区块链安全',
  'AI Security': '人工智能安全',
  'Privacy by Design': '隐私设计',
  'Security by Design': '安全设计',
  'Zero Trust': '零信任',
  'Multi-Factor Authentication': '多因素认证',
  'Single Sign-On': '单点登录',
  'Identity Management': '身份管理',
  'Access Management': '访问管理',
  'Privileged Access Management': '特权访问管理',
  'Data Encryption': '数据加密',
  'Key Management': '密钥管理',
  'Certificate Management': '证书管理',
  'Compliance Monitoring': '合规监控',
  'Risk Monitoring': '风险监控',
  'Threat Monitoring': '威胁监控',
  'Vulnerability Monitoring': '漏洞监控',
  'Performance Monitoring': '性能监控',
  'Availability Monitoring': '可用性监控',
  'User Experience Monitoring': '用户体验监控',
  'Business Monitoring': '业务监控',
  'Log Management': '日志管理',
  'Log Analysis': '日志分析',
  'Log Monitoring': '日志监控',
  'Alerting': '告警',
  'Notification': '通知',
  'Reporting': '报告',
  'Dashboards': '仪表板',
  'Analytics': '分析',
  'Business Intelligence': '商业智能',
  'Data Visualization': '数据可视化',
  'Reporting': '报告',
  'Presentation': '演示',
  'Communication': '沟通',
  'Collaboration': '合作',
  'Document Management': '文档管理',
  'Content Management': '内容管理',
  'Knowledge Management': '知识管理',
  'Records Management': '记录管理',
  'Workflow Management': '工作流管理',
  'Process Management': '流程管理',
  'Project Management': '项目管理',
  'Task Management': '任务管理',
  'Time Management': '时间管理',
  'Resource Management': '资源管理',
  'Asset Management': '资产管理',
  'Inventory Management': '库存管理',
  'Supply Chain Management': '供应链管理',
  'Customer Relationship Management': '客户关系管理',
  'Enterprise Resource Planning': '企业资源计划',
  'Customer Service': '客户服务',
  'Support': '支持',
  'Help Desk': '帮助台',
  'Service Desk': '服务台',
  'IT Service Management': 'IT服务管理',
  'ITIL': 'IT基础设施库',
  'ITSM': 'IT服务管理',
  'SLA': '服务级别协议',
  'KPI': '关键绩效指标',
  'Metrics': '指标',
  'Reporting': '报告',
  'Analytics': '分析',
  'Optimization': '优化',
  'Improvement': '改进',
  'Innovation': '创新',
  'Transformation': '转型',
  'Change': '变化',
  'Adaptation': '适应',
  'Evolution': '进化',
  'Progress': '进步',
  'Growth': '增长',
  'Success': '成功',
  'Achievement': '成就',
  'Excellence': '卓越',
  'Quality': '质量',
  'Value': '价值',
  'Integrity': '正直',
  'Trust': '信任',
  'Respect': '尊重',
  'Professionalism': '专业性',
  'Excellence': '卓越',
  'Innovation': '创新',
  'Collaboration': '合作',
  'Communication': '沟通',
  'Leadership': '领导力',
  'Teamwork': '团队合作',
  'Dedication': '奉献',
  'Passion': '热情',
  'Commitment': '承诺',
  'Accountability': '问责制',
  'Responsibility': '责任',
  'Ownership': '主人翁精神',
  'Initiative': '主动性',
  'Creativity': '创造力',
  'Problem Solving': '问题解决',
  'Critical Thinking': '批判性思维',
  'Decision Making': '决策',
  'Strategic Thinking': '战略思维',
  'Analytical Skills': '分析技能',
  'Technical Skills': '技术技能',
  'Soft Skills': '软技能',
  'Communication Skills': '沟通技能',
  'Interpersonal Skills': '人际技能',
  'Leadership Skills': '领导技能',
  'Management Skills': '管理技能',
  'Team Building': '团队建设',
  'Mentoring': '指导',
  'Coaching': '辅导',
  'Training': '培训',
  'Development': '发展',
  'Learning': '学习',
  'Growth': '成长',
  'Career': '职业',
  'Professional': '专业',
  'Industry': '行业',
  'Market': '市场',
  'Competition': '竞争',
  'Competitive Advantage': '竞争优势',
  'Differentiation': '差异化',
  'Value Proposition': '价值主张',
  'Customer Focus': '客户专注',
  'Customer Centric': '以客户为中心',
  'Quality Focus': '质量专注',
  'Innovation Focus': '创新专注',
  'Efficiency Focus': '效率专注',
  'Sustainability': '可持续性',
  'Environmental': '环境',
  'Social': '社会',
  'Governance': '治理',
  'ESG': '环境、社会和治理',
  'Corporate Social Responsibility': '企业社会责任',
  'Sustainability': '可持续性',
  'Green': '绿色',
  'Eco-friendly': '环保',
  'Renewable': '可再生',
  'Clean Energy': '清洁能源',
  'Carbon Footprint': '碳足迹',
  'Carbon Neutral': '碳中和',
  'Net Zero': '净零排放',
  'Climate Change': '气候变化',
  'Global Warming': '全球变暖',
  'Environmental Protection': '环境保护',
  'Conservation': '保护',
  'Biodiversity': '生物多样性',
  'Ecosystem': '生态系统',
  'Natural Resources': '自然资源',
  'Water Conservation': '水资源保护',
  'Energy Efficiency': '能源效率',
  'Waste Reduction': '减废',
  'Recycling': '回收',
  'Circular Economy': '循环经济',
  'Sustainable Development': '可持续发展',
  'Future': '未来',
  'Tomorrow': '明天',
  'Today': '今天',
  'Yesterday': '昨天',
  'Now': '现在',
  'Later': '稍后',
  'Soon': '很快',
  'Never': '从不',
  'Always': '总是',
  'Forever': '永远',
  'Eternal': '永恒',
  'Time': '时间',
  'Moment': '时刻',
  'Instant': '瞬间',
  'Second': '秒',
  'Minute': '分钟',
  'Hour': '小时',
  'Day': '天',
  'Week': '周',
  'Month': '月',
  'Year': '年',
  'Decade': '十年',
  'Century': '世纪',
  'Millennium': '千年',
  'Era': '时代',
  'Epoch': '纪元',
  'Period': '时期',
  'Phase': '阶段',
  'Stage': '阶段',
  'Step': '步骤',
  'Level': '级别',
  'Tier': '层',
  'Grade': '等级',
  'Rank': '等级',
  'Score': '分数',
  'Rating': '评级',
  'Evaluation': '评估',
  'Assessment': '评估',
  'Review': '审查',
  'Feedback': '反馈',
  'Comment': '评论',
  'Note': '笔记',
  'Memo': '备忘录',
  'Message': '消息',
  'Notification': '通知',
  'Alert': '警报',
  'Warning': '警告',
  'Error': '错误',
  'Issue': '问题',
  'Problem': '问题',
  'Challenge': '挑战',
  'Opportunity': '机会',
  'Solution': '解决方案',
  'Answer': '答案',
  'Question': '问题',
  'Inquiry': '咨询',
  'Request': '请求',
  'Demand': '需求',
  'Supply': '供应',
  'Offer': '提供',
  'Proposal': '提议',
  'Suggestion': '建议',
  'Recommendation': '推荐',
  'Advice': '建议',
  'Guidance': '指导',
  'Direction': '方向',
  'Strategy': '战略',
  'Plan': '计划',
  'Goal': '目标',
  'Objective': '目标',
  'Target': '目标',
  'Aim': '目的',
  'Purpose': '目的',
  'Mission': '使命',
  'Vision': '愿景',
  'Values': '价值观',
  'Principles': '原则',
  'Beliefs': '信念',
  'Philosophy': '哲学',
  'Culture': '文化',
  'Ethics': '道德',
  'Standards': '标准',
  'Quality': '质量',
  'Excellence': '卓越',
  'Innovation': '创新',
  'Creativity': '创造力',
  'Improvement': '改进',
  'Progress': '进步',
  'Success': '成功',
  'Achievement': '成就',
  'Victory': '胜利',
  'Triumph': '胜利',
  'Win': '赢',
  'Lose': '输',
  'Draw': '平局',
  'Tie': '平局',
  'Competition': '竞争',
  'Contest': '竞赛',
  'Game': '游戏',
  'Match': '比赛',
  'Race': '比赛',
  'Championship': '锦标赛',
  'Tournament': '锦标赛',
  'League': '联赛',
  'Series': '系列',
  'Season': '赛季',
  'Team': '团队',
  'Player': '球员',
  'Coach': '教练',
  'Manager': '经理',
  'Owner': '所有者',
  'Fan': '球迷',
  'Audience': '观众',
  'Spectator': '观众',
  'Participant': '参与者',
  'Competitor': '竞争对手',
  'Opponent': '对手',
  'Rival': '对手',
  'Enemy': '敌人',
  'Friend': '朋友',
  'Ally': '盟友',
  'Partner': '合作伙伴',
  'Colleague': '同事',
  'Associate': '同事',
  'Peer': '同龄人',
  'Mentor': '导师',
  'Student': '学生',
  'Teacher': '老师',
  'Instructor': '讲师',
  'Professor': '教授',
  'Researcher': '研究员',
  'Scientist': '科学家',
  'Engineer': '工程师',
  'Developer': '开发者',
  'Designer': '设计师',
  'Artist': '艺术家',
  'Writer': '作家',
  'Editor': '编辑',
  'Publisher': '出版商',
  'Author': '作者',
  'Creator': '创作者',
  'Inventor': '发明家',
  'Entrepreneur': '企业家',
  'Founder': '创始人',
  'CEO': '首席执行官',
  'President': '总裁',
  'Director': '总监',
  'Manager': '经理',
  'Supervisor': '主管',
  'Administrator': '管理员',
  'Operator': '操作员',
  'Technician': '技术员',
  'Specialist': '专家',
  'Consultant': '顾问',
  'Advisor': '顾问',
  'Analyst': '分析师',
  'Planner': '规划师',
  'Coordinator': '协调员',
  'Organizer': '组织者',
  'Leader': '领导',
  'Follower': '追随者',
  'Supporter': '支持者',
  'Advocate': '倡导者',
  'Activist': '活动家',
  'Volunteer': '志愿者',
  'Member': '成员',
  'Subscriber': '订阅者',
  'Customer': '客户',
  'Client': '客户',
  'User': '用户',
  'Guest': '客人',
  'Visitor': '访客',
  'Tourist': '游客',
  'Traveler': '旅行者',
  'Commuter': '通勤者',
  'Resident': '居民',
  'Citizen': '公民',
  'National': '国民',
  'International': '国际',
  'Global': '全球',
  'World': '世界',
  'Universe': '宇宙',
  'Space': '空间',
  'Planet': '行星',
  'Earth': '地球',
  'Sun': '太阳',
  'Moon': '月亮',
  'Star': '星星',
  'Galaxy': '星系',
  'Nebula': '星云',
  'Constellation': '星座',
  'Astronomy': '天文学',
  'Physics': '物理学',
  'Chemistry': '化学',
  'Biology': '生物学',
  'Science': '科学',
  'Technology': '技术',
  'Engineering': '工程',
  'Mathematics': '数学',
  'Statistics': '统计学',
  'Probability': '概率',
  'Logic': '逻辑',
  'Philosophy': '哲学',
  'Psychology': '心理学',
  'Sociology': '社会学',
  'Anthropology': '人类学',
  'History': '历史',
  'Geography': '地理学',
  'Politics': '政治',
  'Economics': '经济学',
  'Business': '商业',
  'Finance': '金融',
  'Marketing': '市场',
  'Sales': '销售',
  'Management': '管理',
  'Law': '法律',
  'Medicine': '医学',
  'Health': '健康',
  'Education': '教育',
  'Art': '艺术',
  'Music': '音乐',
  'Literature': '文学',
  'Theater': '戏剧',
  'Film': '电影',
  'Television': '电视',
  'Radio': '广播',
  'Media': '媒体',
  'Journalism': '新闻业',
  'Communication': '沟通',
  'Language': '语言',
  'Literacy': '识字',
  'Reading': '阅读',
  'Writing': '写作',
  'Speaking': '说话',
  'Listening': '听力',
  'Learning': '学习',
  'Teaching': '教学',
  'Research': '研究',
  'Study': '学习',
  'Exam': '考试',
  'Test': '测试',
  'Quiz': '测验',
  'Assignment': '作业',
  'Project': '项目',
  'Thesis': '论文',
  'Dissertation': '学位论文',
  'Degree': '学位',
  'Certificate': '证书',
  'Diploma': '文凭',
  'Qualification': '资格',
  'License': '许可证',
  'Permit': '许可证',
  'Registration': '注册',
  'Application': '申请',
  'Admission': '入学',
  'Enrollment': '入学',
  'Graduation': '毕业',
  'Commencement': '毕业典礼',
  'Ceremony': '典礼',
  'Celebration': '庆祝',
  'Festival': '节日',
  'Holiday': '假期',
  'Vacation': '度假',
  'Travel': '旅行',
  'Trip': '旅行',
  'Journey': '旅程',
  'Adventure': '冒险',
  'Experience': '体验',
  'Memory': '记忆',
  'Story': '故事',
  'Legend': '传奇',
  'Myth': '神话',
  'Fable': '寓言',
  'Tale': '故事',
  'Narrative': '叙述',
  'History': '历史',
  'Heritage': '遗产',
  'Tradition': '传统',
  'Custom': '习俗',
  'Habit': '习惯',
  'Routine': '例行',
  'Lifestyle': '生活方式',
  'Culture': '文化',
  'Society': '社会',
  'Community': '社区',
  'Neighborhood': '社区',
  'City': '城市',
  'Town': '城镇',
  'Village': '村庄',
  'Country': '国家',
  'Nation': '民族',
  'State': '国家',
  'Republic': '共和国',
  'Kingdom': '王国',
  'Empire': '帝国',
  'Democracy': '民主',
  'Monarchy': '君主制',
  'Dictatorship': '独裁',
  'Communism': '共产主义',
  'Socialism': '社会主义',
  'Capitalism': '资本主义',
  'Economy': '经济',
  'Market': '市场',
  'Trade': '贸易',
  'Commerce': '商业',
  'Industry': '工业',
  'Agriculture': '农业',
  'Manufacturing': '制造业',
  'Services': '服务业',
  'Finance': '金融',
  'Banking': '银行业',
  'Insurance': '保险',
  'Investment': '投资',
  'Real Estate': '房地产',
  'Construction': '建筑',
  'Infrastructure': '基础设施',
  'Transportation': '运输',
  'Logistics': '物流',
  'Telecommunications': '电信',
  'Technology': '技术',
  'Innovation': '创新',
  'Research': '研究',
  'Development': '发展',
  'Education': '教育',
  'Healthcare': '医疗保健',
  'Government': '政府',
  'Politics': '政治',
  'Law': '法律',
  'Justice': '正义',
  'Police': '警察',
  'Military': '军队',
  'Defense': '国防',
  'Security': '安全',
  'Emergency': '紧急',
  'Disaster': '灾难',
  'Crisis': '危机',
  'Response': '响应',
  'Recovery': '恢复',
  'Resilience': '韧性',
  'Adaptation': '适应',
  'Survival': '生存',
  'Growth': '增长',
  'Development': '发展',
  'Progress': '进步',
  'Success': '成功',
  'Happiness': '幸福',
  'Love': '爱',
  'Peace': '和平',
  'Freedom': '自由',
  'Justice': '正义',
  'Equality': '平等',
  'Rights': '权利',
  'Responsibilities': '责任',
  'Duties': '义务',
  'Obligations': '义务',
  'Commitments': '承诺',
  'Promises': '承诺',
  'Agreements': '协议',
  'Contracts': '合同',
  'Treaties': '条约',
  'Alliances': '联盟',
  'Partnerships': '伙伴关系',
  'Relationships': '关系',
  'Connections': '联系',
  'Networks': '网络',
  'Systems': '系统',
  'Structures': '结构',
  'Organizations': '组织',
  'Institutions': '机构',
  'Establishments': '机构',
  'Facilities': '设施',
  'Buildings': '建筑',
  'Homes': '家园',
  'Families': '家庭',
  'Individuals': '个人',
  'People': '人民',
  'Humanity': '人类',
  'Life': '生命',
  'Existence': '存在',
  'Reality': '现实',
  'Truth': '真理',
  'Knowledge': '知识',
  'Wisdom': '智慧',
  'Understanding': '理解',
  'Awareness': '意识',
  'Consciousness': '意识',
  'Mind': '心智',
  'Brain': '大脑',
  'Body': '身体',
  'Spirit': '精神',
  'Soul': '灵魂',
  'Heart': '心脏',
  'Emotion': '情感',
  'Feeling': '感觉',
  'Sensation': '感觉',
  'Perception': '感知',
  'Thought': '思想',
  'Idea': '想法',
  'Concept': '概念',
  'Belief': '信念',
  'Value': '价值',
  'Principle': '原则',
  'Rule': '规则',
  'Law': '法律',
  'Norm': '规范',
  'Standard': '标准',
  'Model': '模型',
  'Pattern': '模式',
  'Structure': '结构',
  'System': '系统',
  'Process': '流程',
  'Method': '方法',
  'Technique': '技术',
  'Tool': '工具',
  'Instrument': '仪器',
  'Equipment': '设备',
  'Machine': '机器',
  'Device': '设备',
  'Product': '产品',
  'Service': '服务',
  'Solution': '解决方案',
  'Result': '结果',
  'Outcome': '结果',
  'Effect': '效果',
  'Impact': '影响',
  'Change': '改变',
  'Transformation': '转型',
  'Evolution': '进化',
  'Revolution': '革命',
  'Innovation': '创新',
  'Discovery': '发现',
  'Invention': '发明',
  'Creation': '创造',
  'Achievement': '成就',
  'Success': '成功',
  'Victory': '胜利',
  'Triumph': '胜利',
  'Glory': '荣耀',
  'Honor': '荣誉',
  'Pride': '自豪',
  'Joy': '快乐',
  'Happiness': '幸福',
  'Love': '爱',
  'Peace': '和平',
  'Harmony': '和谐',
  'Balance': '平衡',
  'Stability': '稳定',
  'Growth': '增长',
  'Prosperity': '繁荣',
  'Abundance': '丰富',
  'Wealth': '财富',
  'Richness': '富足',
  'Plenty': '充足',
  'Sufficiency': '充足',
  'Adequacy': '充分',
  'Excellence': '卓越',
  'Quality': '质量',
  'Perfection': '完美',
  'Completeness': '完整性',
  'Integrity': '完整性',
  'Unity': '团结',
  'Cooperation': '合作',
  'Collaboration': '协作',
  'Teamwork': '团队合作',
  'Partnership': '伙伴关系',
  'Friendship': '友谊',
  'Family': '家庭',
  'Community': '社区',
  'Society': '社会',
  'Humanity': '人类',
  'World': '世界',
  'Universe': '宇宙',
  'Existence': '存在',
  'Life': '生命',
  'Consciousness': '意识',
  'Awareness': '意识',
  'Understanding': '理解',
  'Wisdom': '智慧',
  'Truth': '真理',
  'Reality': '现实',
  'Nature': '自然',
  'Environment': '环境',
  'Ecology': '生态',
  'Ecosystem': '生态系统',
  'Biosphere': '生物圈',
  'Atmosphere': '大气层',
  'Hydrosphere': '水圈',
  'Lithosphere': '岩石圈',
  'Geosphere': '地质圈',
  'Cryosphere': '冰冻圈',
  'Planet': '行星',
  'Earth': '地球',
  'World': '世界',
  'Universe': '宇宙',
  'Space': '空间',
  'Time': '时间',
  'Energy': '能量',
  'Matter': '物质',
  'Mass': '质量',
  'Gravity': '重力',
  'Force': '力',
  'Power': '力量',
  'Strength': '力量',
  'Ability': '能力',
  'Capability': '能力',
  'Capacity': '容量',
  'Potential': '潜力',
  'Possibility': '可能性',
  'Opportunity': '机会',
  'Challenge': '挑战',
  'Risk': '风险',
  'Danger': '危险',
  'Threat': '威胁',
  'Hazard': '危害',
  'Safety': '安全',
  'Security': '安全',
  'Protection': '保护',
  'Defense': '防御',
  'Prevention': '预防',
  'Mitigation': '缓解',
  'Adaptation': '适应',
  'Resilience': '韧性',
  'Recovery': '恢复',
  'Restoration': '恢复',
  'Renewal': '更新',
  'Transformation': '转型',
  'Evolution': '进化',
  'Progress': '进步',
  'Development': '发展',
  'Growth': '增长',
  'Success': '成功',
  'Achievement': '成就',
  'Fulfillment': '实现',
  'Satisfaction': '满足',
  'Happiness': '幸福',
  'Peace': '和平',
  'Love': '爱',
  'Joy': '快乐',
  'Gratitude': '感恩',
  'Appreciation': '欣赏',
  'Respect': '尊重',
  'Honor': '荣誉',
  'Integrity': '正直',
  'Excellence': '卓越',
  'Quality': '质量',
  'Value': '价值',
  'Purpose': '目的',
  'Meaning': '意义',
  'Significance': '重要性',
  'Importance': '重要性',
  'Relevance': '相关性',
  'Impact': '影响',
  'Influence': '影响',
  'Effect': '效果',
  'Consequence': '后果',
  'Outcome': '结果',
  'Result': '结果',
  'Achievement': '成就',
  'Success': '成功',
  'Victory': '胜利',
  'Triumph': '胜利',
  'Glory': '荣耀',
  'Honor': '荣誉',
  'Pride': '自豪',
  'Dignity': '尊严',
  'Respect': '尊重',
  'Admiration': '钦佩',
  'Appreciation': '感激',
  'Gratitude': '感恩',
  'Love': '爱',
  'Affection': '喜爱',
  'Care': '关心',
  'Compassion': '同情',
  'Empathy': '共情',
  'Understanding': '理解',
  'Patience': '耐心',
  'Tolerance': '宽容',
  'Forgiveness': '宽恕',
  'Reconciliation': '和解',
  'Peace': '和平',
  'Harmony': '和谐',
  'Unity': '团结',
  'Cooperation': '合作',
  'Collaboration': '协作',
  'Partnership': '伙伴关系',
  'Friendship': '友谊',
  'Family': '家庭',
  'Community': '社区',
  'Society': '社会',
  'Humanity': '人类',
  'World': '世界',
  'Universe': '宇宙',
  'Existence': '存在',
  'Life': '生命',
  'Consciousness': '意识',
  'Awareness': '意识',
  'Understanding': '理解',
  'Wisdom': '智慧',
  'Truth': '真理',
  'Reality': '现实',
  'Nature': '自然',
  'Beauty': '美丽',
  'Art': '艺术',
  'Music': '音乐',
  'Poetry': '诗歌',
  'Literature': '文学',
  'Philosophy': '哲学',
  'Science': '科学',
  'Technology': '技术',
  'Innovation': '创新',
  'Creativity': '创造力',
  'Imagination': '想象力',
  'Dream': '梦想',
  'Hope': '希望',
  'Faith': '信念',
  'Trust': '信任',
  'Love': '爱',
  'Peace': '和平',
  'Joy': '快乐',
  'Happiness': '幸福',
  'Fulfillment': '实现',
  'Purpose': '目的',
  'Meaning': '意义',
  'Value': '价值',
  'Life': '生命'
};

// 简单翻译函数
function translateText(text) {
  let result = text;
  
  // 先尝试直接匹配
  for (const [english, chinese] of Object.entries(translationMap)) {
    // 匹配整个单词（不区分大小写）
    const regex = new RegExp(`\\b${english}\\b`, 'gi');
    result = result.replace(regex, chinese);
  }
  
  return result;
}

// 创建 Word 文档
async function createTranslatedDocx(inputPath, outputPath) {
  console.log('Reading input file...');
  const text = await readDocx(inputPath);
  
  console.log('Original text length:', text.length);
  console.log('Original text preview:', text.substring(0, 500));
  
  // 按段落分割
  const paragraphs = text.split('\n').filter(p => p.trim());
  console.log('Number of paragraphs:', paragraphs.length);
  
  // 创建文档段落
  const docParagraphs = [];
  
  // 添加标题
  docParagraphs.push(
    new Paragraph({
      text: 'PSM发货报告（中文翻译）',
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 400
      }
    })
  );
  
  // 翻译并添加每个段落
  for (const paragraph of paragraphs) {
    const translatedText = translateText(paragraph.trim());
    
    // 判断是否是标题
    if (paragraph.length < 50 && paragraph === paragraph.toUpperCase()) {
      docParagraphs.push(
        new Paragraph({
          text: translatedText,
          heading: HeadingLevel.HEADING_2,
          spacing: {
            before: 200,
            after: 100
          }
        })
      );
    } else {
      docParagraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: translatedText,
              size: 24 // 12pt
            })
          ],
          spacing: {
            after: 200
          }
        })
      );
    }
  }
  
  // 创建文档
  const doc = new Document({
    sections: [{
      properties: {},
      children: docParagraphs
    }]
  });
  
  console.log('Creating output file...');
  const buffer = await Packer.toBuffer(doc);
  
  // 保存文件
  fs.writeFileSync(outputPath, buffer);
  console.log('File saved successfully:', outputPath);
}

// 主函数
async function main() {
  const inputFile = '/tmp/psm-report.docx';
  const outputFile = '/tmp/psm-report-chinese.docx';
  
  console.log('Starting translation...');
  await createTranslatedDocx(inputFile, outputFile);
  console.log('Translation completed!');
}

main().catch(error => {
  console.error('Error:', error);
  process.exit(1);
});
